/* Full body content for every library article, keyed by slug.
   Written for the Hombre de Barro library. Strapi can override
   per-article from the admin panel. */

import type { Articulo } from "./types";

type Block = NonNullable<Articulo["contenido"]>[number];

// Small helpers to keep the literal compact and readable.
const p = (text: string): Block => ({
  type: "paragraph",
  children: [{ text }],
});

const h = (level: 2 | 3, text: string): Block => ({
  type: "heading",
  level,
  children: [{ text }],
});

const ul = (...items: string[]): Block => ({
  type: "list",
  format: "unordered",
  children: items.map((text) => ({
    type: "list-item",
    children: [{ text }],
  })),
});

const ol = (...items: string[]): Block => ({
  type: "list",
  format: "ordered",
  children: items.map((text) => ({
    type: "list-item",
    children: [{ text }],
  })),
});

export const ARTICULO_CONTENT: Record<string, Block[]> = {
  /* ── Muros y Estructura ─────────────────────────────────── */
  "adobe-paso-a-paso": [
    p("El adobe es el material constructivo más antiguo y democrático que conocemos. Bien hecho, es noble, durable y silenciosamente sofisticado: regula la humedad interior, acumula calor del sol y se devuelve a la tierra cuando ya no se usa."),
    h(2, "Probar la tierra"),
    p("Antes de mezclar, hay que conocer el suelo. Tomá una muestra a 40 cm de profundidad — la capa orgánica superficial no sirve."),
    ul(
      "Prueba del frasco: llenar un frasco con un tercio de tierra y dos tercios de agua, agitar y dejar reposar 24 hs. Las capas que sedimentan te dan la composición — buscamos 15–30 % arcilla, 40–55 % limo, 15–30 % arena.",
      "Prueba de la cinta: amasar un cilindro y extenderlo entre los dedos. Si la cinta llega a 10–15 cm antes de romperse, el contenido de arcilla es adecuado.",
      "Prueba de la caída: una bolita de tierra húmeda dejada caer desde un metro. Si se deforma sin desarmarse, está en punto.",
    ),
    h(2, "La mezcla"),
    p("Las proporciones varían según el suelo. Una receta de partida confiable:"),
    ul(
      "70 % tierra cribada (zarandeada por malla de 8 mm)",
      "20 % arena fina, sólo si la tierra es muy arcillosa",
      "10 % paja larga (5–10 cm), como armadura interna",
      "Agua: suficiente para amasar sin que la mezcla se pegue a la espátula",
    ),
    p("La mezcla descansa 24 hs antes de moldear. Ese reposo hidrata la arcilla y previene fisuras de retracción."),
    h(2, "Moldeo y secado"),
    p("Los moldes de madera tradicionales son de 38×19×9 cm. Se mojan antes de cada uso para que el barro no se adhiera. Se rellena, se golpea para sacar aire, se enrasa con un listón, y se desmolda inmediatamente sobre una superficie llana y aireada."),
    p("El secado lleva 21–30 días en clima templado, con dos vueltas intermedias para garantizar uniformidad. En zonas húmedas conviene cubrir con paja para una sombra ventilada. Adobes que llueven antes de estar secos se pueden recuperar; los que se quiebran en dos antes de estar curados, no."),
    h(2, "Aparejo y muros"),
    p("Para muros portantes de planta baja, conviene un espesor mínimo de 40 cm. El aparejo a tope con junta de barro de 1,5 cm es lo más simple; el aparejo a la inglesa (alternando soga y tizón) da mucha más cohesión y es el que recomendamos para muros de carga."),
    p("Si las paredes superan los 3,5 m de altura libre, agregar un encadenado intermedio de madera o un dintel continuo de hormigón armado distribuye las cargas y evita el pandeo."),
  ],

  "plano-quincha-mejorada": [
    p("Plano descargable para una vivienda de 90 m² en quincha mejorada. Diseñada para la zona centro-norte de Argentina, con orientación norte óptima, una galería pasiva y un sistema constructivo verificable contra el reglamento CIRSOC 601."),
    h(2, "Sistema constructivo"),
    p("La quincha mejorada combina un esqueleto portante de madera rolliza con un cierre de muros de barro armado entre dos bastidores de caña tacuara. El resultado: muros livianos (220 kg/m³), elásticos y disipativos."),
    ul(
      "Cimientos: hormigón ciclópeo (60 % piedra de la zona) con sobrecimiento de hormigón armado de 40 cm.",
      "Estructura: postes de eucalipto colorado ø 12–15 cm cada 2,40 m, vigas perimetrales de eucalipto saligna.",
      "Muros: dos bastidores paralelos de caña tacuara cada 6 cm; relleno de barro + arena + paja larga, espesor total 18–22 cm.",
      "Cubierta: dos aguas a 35° en madera local con aislación de lana de oveja + barrera de vapor.",
      "Revoque: dos capas de barro (gruesa + fina) más una mano de aceite de lino en exteriores expuestos.",
    ),
    h(2, "Distribución (90 m²)"),
    p("Planta libre orientada al norte para captación solar pasiva. Tres habitaciones al sur — más frescas en verano. Cocina-comedor al norte con galería de 1,80 m de profundidad: protege en verano (sol alto) y deja entrar la radiación en invierno (sol bajo). Baño compacto en el centro, próximo a las habitaciones."),
    h(2, "Detalles incluidos en el plano"),
    ol(
      "Implantación con orientación solar.",
      "Planta arquitectónica acotada.",
      "Cortes longitudinal y transversal.",
      "Detalle de encuentro cimiento-muro (impermeabilización capilar).",
      "Detalle de nudo poste-viga (vínculo metálico galvanizado).",
      "Planilla de carpinterías.",
      "Memoria descriptiva con cómputo aproximado.",
    ),
    h(2, "Costo orientativo"),
    p("Construcción completa con materiales locales y mano de obra contratada: aproximadamente USD 800/m² a mayo 2026. Con autoconstrucción y mingas, baja a USD 550–600/m²."),
    p("El plano es una base. Cada terreno y cada cliente lo modifica — la idea es ofrecer un punto de partida verificable y completo, no una solución única."),
  ],

  "tapial-vs-adobe-vs-cob": [
    p("Las tres grandes técnicas de construcción en tierra cruda son adobe, tapial y cob. No son intercambiables: cada una pide un tipo de tierra, un clima y un ritmo de obra distinto. Esta guía las compara en seis dimensiones."),
    h(2, "Adobe"),
    p("Ladrillos de barro moldeados, secados al sol y luego aparejados con junta de barro. Es la técnica más versátil: se puede prefabricar lejos de la obra, se trabaja en módulos chicos y permite reparaciones puntuales."),
    ul(
      "Tierra: arcillosa (15–30 % arcilla), tolerante a variaciones.",
      "Mano de obra: media — un equipo entrenado en una semana.",
      "Velocidad: lenta — el secado es el cuello de botella (3–4 semanas).",
      "Clima: templado a árido. En zonas muy lluviosas, sólo bajo aleros generosos.",
    ),
    h(2, "Tapial"),
    p("Tierra apisonada in situ dentro de un encofrado. Es la técnica con mejor terminación arquitectónica — los muros muestran las tongadas como vetas de roca sedimentaria — y la que ofrece mayor masa térmica."),
    ul(
      "Tierra: limo-arenosa, baja en arcilla (8–18 %).",
      "Mano de obra: alta — requiere equipo especializado en encofrado y compactación.",
      "Velocidad: media — un metro lineal de muro por día y equipo.",
      "Clima: templado a árido. Excelente comportamiento en climas con amplitud térmica fuerte.",
    ),
    h(2, "Cob"),
    p("Monolítico, esculpido a mano con bochones de barro armado. Sin moldes, sin encofrado. Es la técnica que permite las formas más libres (curvas, nichos, bancos integrados al muro)."),
    ul(
      "Tierra: arcillosa con fibra natural larga (paja, espadaña).",
      "Mano de obra: baja barrera de entrada — ideal para autoconstrucción y mingas.",
      "Velocidad: muy lenta — un muro de 1 m de altura por capa, esperando 2 días entre capas.",
      "Clima: templado-húmedo a templado. Necesita zócalo y alero generosos.",
    ),
    h(2, "Cuál elegir"),
    p("Si tu prioridad es prefabricar y trabajar por etapas, adobe. Si querés muros monolíticos con gran inercia térmica, tapial. Si la obra tiene formas curvas o querés involucrar a la gente en autoconstrucción participativa, cob."),
    p("En la práctica, la mayoría de los proyectos de Hombre de Barro combinan dos o tres: zócalos de tapial con muros de adobe, o adobe con cob esculpido en zonas específicas (bancos, nichos, hornos)."),
  ],

  "superadobe-earthbag": [
    p("Superadobe es construir con sacos de polipropileno rellenos de tierra estabilizada. Lo desarrolló el arquitecto iraní Nader Khalili en los años 80 como respuesta a la necesidad de refugios sismo-resistentes de emergencia. Hoy es una técnica madura que se usa para viviendas permanentes, bóvedas y domos."),
    h(2, "Cómo funciona"),
    p("Los sacos se llenan en obra con tierra húmeda (12–18 % humedad), se tienden por hiladas y se compactan a pisón. Entre cada hilada va una doble vuelta de alambre de púas que actúa como armadura tensora — impide que las hiladas se desplacen horizontalmente bajo cargas sísmicas o laterales."),
    p("Es probablemente la técnica de tierra más resistente a los sismos: el conjunto trabaja como una pared celular flexible. Tests del Cal-Earth Institute la han llevado a aceleraciones del 0,5 g sin colapso."),
    h(2, "Cuándo usarla"),
    ul(
      "Bóvedas, cúpulas y domos — la geometría compresiva es ideal para sacos compactados.",
      "Muros de contención.",
      "Construcciones rápidas en sitios remotos o de emergencia.",
      "Zonas sísmicas exigentes (zona 3 o 4 de Argentina).",
    ),
    h(2, "Estabilización de la tierra"),
    p("Para construcción permanente, la tierra dentro del saco se estabiliza con 5–10 % de cemento o cal aérea. Esto garantiza que, si los sacos se degradan con el tiempo (los rayos UV los hacen frágiles), el contenido mantiene la cohesión."),
    h(2, "Acabado"),
    p("El saco crudo no es bonito ni durable. Toda la obra debe revocarse — dos manos de barro grueso para regularizar la superficie, una mano de barro fino, y una capa protectora final (cal hidratada o aceite de lino, según exposición)."),
    h(2, "Limitaciones"),
    p("La velocidad es baja: 2–3 m² de muro por día con un equipo de dos personas. El consumo de polipropileno (sacos) es alto — buscar sacos de segunda mano de bolsas de arpillera es una manera de bajar ese impacto. Y la altura máxima sin refuerzos estructurales adicionales es modesta — más allá de 3 m, conviene combinarla con elementos de madera o tensores adicionales."),
  ],

  /* ── Techos y Cubiertas ─────────────────────────────────── */
  "techo-verde-extensivo": [
    p("Un techo verde extensivo es una cubierta vegetal de bajo mantenimiento, sustrato delgado (8–15 cm) y plantas autosuficientes — sedum, gramíneas nativas, suculentas. Pesa entre 80 y 170 kg/m² saturado, es decir, dentro del rango admisible para la mayoría de las losas convencionales de hormigón armado."),
    h(2, "Beneficios"),
    ul(
      "Aislación térmica: equivalente a 6–8 cm de lana de vidrio, sin huella industrial.",
      "Inercia: amortigua los picos de temperatura interior 4–6 °C en verano.",
      "Retención pluvial: el sustrato retiene el 50–70 % de la lluvia anual, atenuando picos de escorrentía.",
      "Biodiversidad: nidos, polinizadores, refugio para insectos nativos.",
      "Vida útil: 40–60 años, contra los 15–25 años de una membrana asfáltica tradicional expuesta al sol.",
    ),
    h(2, "Las siete capas (de abajo hacia arriba)"),
    ol(
      "Losa estructural — hormigón armado, madera maciza o panel SIP con luces calculadas para 200 kg/m² mínimo.",
      "Membrana impermeabilizante — EPDM o membrana líquida poliuretánica, resistente a la raíz.",
      "Barrera antirraíz — geotextil específico (necesario si la membrana no es resistente a raíz).",
      "Capa de drenaje — placa drenante de polietileno con cazoletas (5–6 cm) o capa de árido (8–10 cm de canto rodado lavado).",
      "Geotextil de retención — separa el drenaje del sustrato y filtra finos.",
      "Sustrato — mezcla específica: 40 % arena, 30 % árido volcánico (perlita, pómez), 20 % compost, 10 % tierra negra.",
      "Vegetación — autóctonas de cubierta plana resistente a sequía.",
    ),
    h(2, "Cálculo estructural"),
    p("Para una losa de hormigón armado convencional de 12 cm de espesor: capacidad portante aproximada 350 kg/m² al límite, con 200 kg/m² disponibles para sobrecarga. Un techo verde extensivo saturado se ubica entre 80–170 kg/m², dejando margen para nieve (donde aplique) y mantenimiento."),
    p("Para cubiertas de madera con vigas a 50 cm de eje y un panel de 22 mm de OSB sobre clavadores, conviene reforzar a vigas dobles o reducir el sustrato a 8 cm máximo."),
    h(2, "Vegetación recomendada en zona centro Argentina"),
    ul(
      "Sedum acre, S. reflexum, S. spurium — el clásico, baja mantenimiento.",
      "Gramíneas: Eragrostis curvula, Stipa caudata, Nassella tenuissima.",
      "Florales: Verbena bonariensis, Glandularia perakii, Sphaeralcea bonariensis.",
      "Aromáticas: tomillo serpol, orégano vulgar — comestibles, resistentes, y útiles para el polinizador.",
    ),
    p("Plantarse en otoño o final del invierno, regar las primeras 6–8 semanas y después dejar al sistema autorregularse. El primer año conviene controlar invasoras manualmente; del segundo en adelante, basta con una poda anual."),
  ],

  "techo-reciproco": [
    p("Un techo recíproco es una estructura autoportante en la que cada viga apoya sobre la siguiente formando un anillo que cierra sobre sí mismo. No hay columna central, no hay cumbrera. Es estable, eficiente en material, y permite vanos de 6–8 m sin elementos intermedios."),
    h(2, "Geometría"),
    p("El sistema funciona con cualquier número de vigas mayor o igual a tres. Lo típico son 6, 8 o 12 vigas. Mientras más vigas, más cerca de un círculo y más pequeño el ojo central — el hueco que queda en la corona."),
    p("Cada viga descansa sobre la siguiente en una posición rotada un ángulo igual a 360°/n grados. La forma final es un cono trunco con un óculo en el centro — ese óculo se puede cerrar con un vidrio fijo y se convierte en una claraboya cenital generosa."),
    h(2, "Materiales"),
    ul(
      "Rollos de eucalipto colorado o saligna de ø 15–20 cm, secos al menos 6 meses bajo techo.",
      "Largo: 1,3 veces el radio del círculo de apoyo (para una luz de 6 m, vigas de 4 m).",
      "Sujetadores: tornillos M12 o pasadores roscados con clavijas de madera dura.",
      "Cubierta sobre las vigas: tablazón de 22 mm + aislación + membrana + chapa o tejuela.",
    ),
    h(2, "Armado paso a paso"),
    ol(
      "Definir el anillo de apoyo (encadenado superior de los muros).",
      "Apuntalar provisoriamente la primera viga en el centro con un poste vertical.",
      "Apoyar la segunda viga sobre la primera, a la altura calculada (un tercio de la luz desde el centro).",
      "Continuar con cada viga, rotando el ángulo correspondiente, hasta cerrar el círculo.",
      "Cuando todas las vigas están apoyadas mutuamente, retirar el puntal central — la estructura queda en equilibrio.",
      "Vincular los apoyos con tornillos o pasadores antes de cargar la cubierta.",
    ),
    h(2, "Cálculo de cargas"),
    p("Para una luz de 6 m con 8 vigas de eucalipto rollizo ø 18 cm, la flecha bajo carga muerta + nieve (50 kg/m²) se mantiene dentro de L/250. Para luces mayores, se incrementa el diámetro o se duplican vigas alternadas."),
    p("Verificar siempre con un profesional. La estructura es elegante pero atípica — un calculista que no conoce el sistema puede sobredimensionar mucho."),
  ],

  "cubiertas-paja-junco": [
    p("La cubierta de paja o junco — el ranchero pampeano clásico — es una de las soluciones más sostenibles que existen para climas templados. Material de cosecha local, vida útil de 25–40 años, aislación equivalente a 15 cm de lana de vidrio y una belleza que sólo el tiempo enseña."),
    h(2, "Materiales"),
    p("En Argentina los tres materiales tradicionales son la paja brava (Stipa caudata), el junco (Schoenoplectus), y la totora (Typha latifolia). Hoy también se usa paja de centeno y de trigo cuando la cosecha lo permite."),
    p("Se cosecha en plena madurez (febrero-marzo), se ata en gavillas de 30–40 cm de diámetro y se deja secar 4–6 semanas bajo techo ventilado. Cualquier humedad atrapada al armar la cubierta es el principio del moho."),
    h(2, "Inclinación"),
    p("La regla práctica: 45° mínimo. A menor inclinación, la lluvia penetra entre las pajas en vez de correr por la superficie. Lo óptimo es entre 50 y 60° — bonito y funcional. A más de 70° empieza a despeinarse con viento fuerte."),
    h(2, "Atado"),
    p("Los manojos se atan al pero (listón horizontal de la estructura) con alambre o tiento, cubriendo el atado de la fila anterior con la base de la siguiente. Esto garantiza que el agua no encuentra una entrada al interior. El espesor terminado es de 25–35 cm."),
    h(2, "Mantenimiento"),
    p("Año 1–5: revisión visual cada primavera, reposición de manojos perdidos por viento. Año 5–15: peinado anual con horquilla, descarte de manojos que muestran moho. Año 15–25: reemplazo parcial cada 5 años de las dos hiladas superiores (las más castigadas por sol y agua)."),
    p("Hay cubiertas de paja en El Bolsón y en Tafí del Valle que llegan a 50 años con mantenimiento cuidadoso. La clave es ventilación: el lado interior de la cubierta nunca debe quedar atrapado contra una membrana impermeable. El aire que circula es lo que evita la pudrición."),
  ],

  "techo-verde-intensivo": [
    p("El techo verde intensivo es el primo grande del extensivo: sustrato más profundo (25–80 cm), plantas más exigentes, mantenimiento periódico — pero también muchísima más productividad. En su versión más ambiciosa se vuelve huerta urbana en altura."),
    h(2, "Diferencias con el extensivo"),
    ul(
      "Sustrato: 25–80 cm (vs. 8–15 cm en extensivo).",
      "Peso saturado: 350–800 kg/m² (vs. 80–170 kg/m²).",
      "Riego: imprescindible — al menos goteo automatizado.",
      "Mantenimiento: similar a un jardín de patio, con poda y reposición estacional.",
      "Vegetación: tomates, lechugas, hierbas aromáticas, arbustos, incluso frutales enanos.",
    ),
    h(2, "Refuerzo estructural"),
    p("La gran diferencia es estructural. Una cubierta extensiva sirve sobre losa estándar; una intensiva requiere refuerzo deliberado. Para una losa de hormigón armado convencional, hay que pasar de 12 cm a 18–20 cm de espesor, o reforzar con vigas T cada 50 cm."),
    p("Para cubiertas de madera, pasamos a vigas de 7×24 cm a 40 cm de eje, sobre soporte mínimo de 1,5 mm de chapa o panel OSB doble."),
    h(2, "Diseño del riego"),
    p("Goteo enterrado a 10 cm de profundidad con líneas separadas 30 cm. Un programador estacional ajusta frecuencia: 2 veces por semana en invierno, hasta 1 vez por día en verano. Un sensor de humedad evita riego cuando llueve."),
    p("Si se combina con captación pluvial, una cisterna de 2.000 litros por cada 30 m² de huerta de techo es suficiente para climas templados argentinos."),
    h(2, "Cultivos recomendados"),
    ul(
      "Verduras de hoja: lechugas, acelga, espinaca — ciclos rápidos, raíz superficial.",
      "Aromáticas: albahaca, perejil, tomillo, romero — perennes, bajo mantenimiento.",
      "Tomates cherry y ají: necesitan tutoreo simple, dan abundante.",
      "Frutales enanos: arándanos, frutillas, en macetones integrados al sustrato.",
    ),
    p("Una huerta intensiva bien planeada da 4–6 kg de hortaliza por m² por año. Y, además, sigue cumpliendo todas las funciones del techo verde: aislación, retención pluvial, refugio de polinizadores."),
  ],

  /* ── Agua y Saneamiento ─────────────────────────────────── */
  "fitodepuracion-plano": [
    p("Una planta de fitodepuración es un humedal artificial: un sistema de plantas macrófitas (juncos, espadañas, papiros) y micro-organismos que tratan aguas residuales sin energía eléctrica. Para una familia de 4–8 personas se dimensiona en 20–40 m² y trata el 100 % del agua residual doméstica."),
    h(2, "Etapas del tratamiento"),
    ol(
      "Tratamiento primario (cámara séptica de 2 compartimentos): retiene sólidos y empieza la digestión anaeróbica. Volumen: 1.500–3.000 L según familia.",
      "Tratamiento secundario (humedal de flujo subsuperficial horizontal): el agua circula a través de un lecho de grava (40 cm) sembrado con macrófitas. Aquí ocurre el 80 % del trabajo de remoción de nutrientes y bacterias.",
      "Tratamiento terciario (humedal de flujo libre o estanque de pulido, opcional): da el último brillo al agua antes del vertido o reuso.",
    ),
    h(2, "Dimensionamiento"),
    p("Regla simple: 5 m² de humedal por persona. Para una familia de 5: 25 m². La proporción largo:ancho ideal es 3:1 — un rectángulo de 8,5 × 3 m funciona bien."),
    p("Profundidad del lecho: 60 cm total, con grava gruesa (40–80 mm) abajo, grava media (10–20 mm) arriba, y los últimos 10 cm de grava fina (5–10 mm) donde se siembran las raíces."),
    h(2, "Selección de plantas"),
    ul(
      "Typha latifolia (totora) — la más usada, robusta, fácil de conseguir.",
      "Schoenoplectus tabernaemontani (junco lacustre) — buena tolerancia al frío.",
      "Cyperus papyrus o Cyperus alternifolius (papiro) — estética + función.",
      "Iris pseudacorus (lirio amarillo) — floración decorativa, raíz potente.",
    ),
    p("Se planta a 4 plantas/m² mínimo. En 8–10 meses cubren todo el lecho y el sistema entra en operación plena."),
    h(2, "Operación y mantenimiento"),
    ul(
      "Anual: poda de los tallos secos al final del invierno.",
      "Cada 5–7 años: vaciar y revisar la cámara séptica.",
      "Cada 15–20 años: lavado o reemplazo de la grava (sólo si se observa colmatación).",
    ),
    p("El agua tratada — entre 95 y 99 % limpia, sin patógenos — se puede reutilizar para riego de árboles ornamentales o vertido a zanja de absorción. Es ilegal usarla para riego de huerta comestible, aunque técnicamente cumple los parámetros."),
  ],

  "biodigestor-casero": [
    p("Un biodigestor convierte materia orgánica (excretas de ganado, restos vegetales) en dos productos útiles: biogás (mezcla de metano + CO₂ que se quema en cocina o calefacción) y biol (fertilizante líquido). Es una tecnología sencilla, antigua y subutilizada en Argentina."),
    h(2, "El biodigestor tubular"),
    p("La versión casera más extendida es el biodigestor tubular o de polietileno: una bolsa de 1 m de diámetro por 6–10 m de largo enterrada parcialmente en una zanja con pendiente. Es barato (USD 200–400 en materiales), durable (8–12 años) y eficiente para climas templados."),
    h(2, "Materiales"),
    ul(
      "Manga de polietileno tubular de 200 micras, ancho 1 m, largo 8 m.",
      "Dos tubos PVC de 110 mm (entrada y salida) y dos codos.",
      "Válvula de paso y manguera para el gas (4 m).",
      "Botella de plástico flexible como trampa de agua (válvula de seguridad).",
    ),
    h(2, "Construcción"),
    ol(
      "Excavar una zanja trapezoidal: 0,9 m de ancho arriba, 0,6 m abajo, 1 m de profundidad, 8 m de largo.",
      "Inflar la manga con un soplador y atarla a los tubos de entrada/salida (PVC de 110 mm).",
      "Colocar la manga en la zanja, dejando 1/3 fuera del nivel del suelo (la parte de la 'cúpula' de gas).",
      "Conectar la salida de gas con manguera + válvula a la cocina o tanque acumulador.",
      "Cargar con 50 % de estiércol fresco (1.500 kg de bosta vacuna mezclada con agua) + 50 % de agua. Sellar.",
      "Esperar 21–30 días para producción estable.",
    ),
    h(2, "Mantenimiento"),
    p("Carga diaria: 20–40 L de mezcla 50/50 estiércol+agua. Es importante mantener constancia — el digestor anaeróbico funciona mejor con un flujo regular que con cargas intermitentes."),
    p("La trampa de agua se purga semanalmente. Un olor a sulfuro intenso indica desbalance: agregar agua y reducir carga por unos días."),
    h(2, "Producción esperada"),
    p("Un biodigestor tubular de 8 m³ produce entre 1 y 2 m³ de biogás diario — suficiente para 2–3 horas diarias de cocina. El biol se extrae 1 vez por semana del extremo de salida, diluido al 50 % se aplica al riego de árboles."),
  ],

  "captacion-agua-lluvia": [
    p("Captar agua de lluvia es un acto político: te desconecta del monopolio del agua corriente y te conecta al ciclo del propio terreno. Bien diseñado, un sistema de captación abastece todo el consumo doméstico de una familia incluso en zonas con 600 mm anuales de precipitación."),
    h(2, "Cuánta agua se puede captar"),
    p("La fórmula simple: superficie de techo en m² × precipitación anual en mm × 0,85 (coeficiente de pérdida) = litros captados por año."),
    p("Ejemplo: una casa de 100 m² de techo en zona centro de Argentina (800 mm/año): 100 × 800 × 0,85 = 68.000 L/año. Una familia de 4 con consumo eficiente (60 L/persona/día) usa 87.600 L/año. Con techos de 130 m² + cisterna de almacenamiento, son completamente autónomos."),
    h(2, "Componentes"),
    ol(
      "Techo limpio (sin tejas asfálticas — soltan partículas) — chapa, teja cerámica o cubierta vegetal extensiva (sí, también capta).",
      "Canaletas con pendiente del 1 % y bajadas de PVC de 100 mm.",
      "First flush — dispositivo que desvía los primeros 1–2 L/m² para limpiar el techo después de una sequía larga.",
      "Filtro de hojas/insectos en la entrada al tanque.",
      "Cisterna: hormigón armado o polietileno, dimensión ≥ 60 días de consumo (10.000–20.000 L para una familia).",
      "Bomba de presión (jet o periférica) + tanque hidroneumático.",
      "Filtros finales: sedimentos (5 micras) + carbón activado + UV o cerámico de plata coloidal para potabilización.",
    ),
    h(2, "Dimensionamiento de la cisterna"),
    p("La regla pragmática: capacidad de cisterna = consumo de la familia × días entre lluvias importantes. En zona centro, donde llueve cada 10–14 días en promedio: 4 personas × 60 L/día × 60 días = 14.400 L. Un tanque de 15.000 L cubre con margen."),
    h(2, "Costo"),
    p("Para una familia de 4 con consumo eficiente, una instalación completa (cisterna 15.000 L de PRFV + bomba + filtros + UV) ronda USD 1.500–2.500 según calidad. La amortización frente al consumo de Aguas Cordobesas es 6–9 años. Después: agua gratis, propia, blanda, sin cloro."),
  ],

  "bano-seco-compostero": [
    p("Un baño seco compostero separa nuestras excretas en dos productos útiles: humus para suelos y, opcionalmente, orina como fertilizante líquido. Sin agua, sin cloaca, sin contaminación. Bien diseñado, es más higiénico y menos olor que un baño con descarga."),
    h(2, "El principio"),
    p("Las heces se compostan en una cámara aireada, secas (humedad < 50 %), con una proporción C:N de aproximadamente 30:1 — eso significa agregar material seco rico en carbono (aserrín, ceniza, hojas secas) cada vez que se usa. En 8–12 meses el contenido se transforma en humus inodoro."),
    h(2, "Tipologías"),
    ul(
      "Doble cámara alternada: dos cámaras, mientras una se llena la otra composta. Una vez al año se rotan. La más usada en autoconstrucción.",
      "De rotación tipo Clivus Multrum: una sola cámara grande con pendiente — las heces frescas entran arriba, el humus maduro se retira abajo.",
      "Con separador de orina: la orina cae en un compartimento aparte (se diluye y se usa como fertilizante), las heces sólo van a la cámara. Reduce mucho el olor y el volumen.",
    ),
    h(2, "Ventilación"),
    p("Imprescindible. Un tubo de ventilación de PVC de 110 mm sube desde la cámara hasta sobrepasar el techo, con un extractor eólico o un pequeño extractor solar de 12 V. La depresión negativa generada saca cualquier olor a través del tubo, NO del inodoro."),
    h(2, "Normativa argentina"),
    p("No existe una norma nacional específica. Algunos municipios (El Bolsón, Beltrán, La Serranita) los habilitan explícitamente; en la mayoría de los casos se trata como sistema individual de tratamiento, asimilable a una cámara séptica. Conviene consultar antes de construir."),
    h(2, "Mitos comunes"),
    ul(
      "\"Huele mal\" — no, si está bien ventilado. Huele a tierra húmeda, no a baño público.",
      "\"Hay moscas\" — no, si el tubo de ventilación lleva malla anti-insectos y el material seco se agrega después de cada uso.",
      "\"No es higiénico\" — al revés. Después de 8 meses de compostaje a 30+ °C, los patógenos comunes mueren. El humus resultante es seguro para árboles ornamentales o frutales no comestibles directos.",
    ),
  ],

  /* ── Energía ─────────────────────────────────────────────── */
  "muro-trombe": [
    p("El muro Trombe es el sistema de calefacción solar pasiva más antiguo y elegante: un muro de gran masa térmica orientado al norte (en hemisferio sur), pintado oscuro, con un vidriado a unos 15 cm de distancia. El sol calienta el muro durante el día; el muro entrega calor al interior durante la noche."),
    h(2, "Cómo funciona"),
    p("Tres mecanismos simultáneos:"),
    ul(
      "Conducción: el calor atraviesa el muro y entra al interior unas 8–10 horas después.",
      "Convección: si el muro tiene aberturas arriba y abajo, el aire caliente entre vidrio y muro asciende, entra al interior por arriba, y el aire frío del interior baja por las aberturas inferiores — circulación natural.",
      "Radiación: la cara interior del muro emite radiación infrarroja hacia el interior una vez que el aire ya entregó su calor.",
    ),
    h(2, "Dimensionamiento"),
    p("Regla orientativa para zona centro de Argentina: el muro Trombe debe ocupar 15–25 % del área del piso del ambiente que calefacciona, y orientarse a ± 15° del norte verdadero."),
    p("Para un ambiente de 25 m²: 4–6 m² de muro Trombe. Si el muro es de 50 cm de espesor en adobe, da inercia para 12 horas; si es de 30 cm en mampostería pesada, para 8 horas."),
    h(2, "Materiales y construcción"),
    ul(
      "Muro: adobe (mejor), tapial, o ladrillo macizo de 30–50 cm. Pintado de un color oscuro mate (negro, marrón oscuro). El brillo reduce la absorción.",
      "Vidriado: doble vidrio hermético (DVH) separación 8–12 mm. Distancia al muro: 12–18 cm.",
      "Marco: madera o aluminio con ruptura térmica. Aislación lateral importante — el calor del aire intersticial debe quedarse ahí.",
      "Aberturas opcionales (para circulación de aire): dos en la parte alta y dos en la baja del muro, cada una de 5 × 30 cm. Compuertas para cerrarlas en verano.",
    ),
    h(2, "Verano"),
    p("Sin previsiones, un muro Trombe sobrecalienta el verano. Soluciones:"),
    ul(
      "Alero o parasol horizontal calculado para que el sol del solsticio de verano (mediodía a 79° en zona centro) no llegue al vidriado.",
      "Cortinas opacas exteriores plegables (las interiores no sirven — el calor ya está adentro del vidrio).",
      "Ventilación nocturna profunda para descargar el calor acumulado.",
    ),
    h(2, "Costo"),
    p("Un muro Trombe de 6 m² en adobe + DVH cuesta entre USD 800 y 1.500 según calidad del vidriado. Reduce 40–60 % la demanda de calefacción en invierno frente a un muro convencional norte sin masa térmica."),
  ],

  "estufa-rusa-masa-termica": [
    p("La estufa rusa, también llamada estufa de masa o de inercia, es lo opuesto a una estufa de hierro: en vez de irradiar mientras quema, acumula el calor del fuego en una gran masa cerámica y lo libera durante 12–24 horas después. Una sola carga matutina calienta toda la casa hasta el día siguiente."),
    h(2, "Anatomía"),
    p("Cinco partes funcionales:"),
    ol(
      "Cimiento aislado del suelo (ladrillo + capa térmica).",
      "Cámara de combustión cerrada con puerta hermética de hierro fundido.",
      "Sistema de bafles cerámicos — el humo recorre un circuito de 4–8 m antes de salir, transfiriendo casi todo su calor a la masa.",
      "Cuerpo principal (la masa) — ladrillos macizos o piedra. 1.500–3.000 kg total.",
      "Banco calefactor o nicho — la última parte del recorrido del humo, accesible para sentarse o dormir.",
    ),
    h(2, "Combustión limpia"),
    p("La cámara de combustión opera a 800–900 °C — temperaturas a las que la quema de leña es casi completa. La eficiencia ronda el 85 % (contra 35–50 % de una salamandra de hierro tradicional) y las emisiones de partículas son 1/10."),
    h(2, "Dimensionamiento"),
    p("Una estufa rusa estándar (1.800 kg, banco de 2,4 × 0,6 m) calefacciona aproximadamente 60–80 m² en zona centro de Argentina. Para casas de 120–150 m² conviene una estufa más grande (2.500 kg) o dos estufas chicas conectadas."),
    h(2, "Materiales"),
    ul(
      "Ladrillos macizos comunes (NO huecos) — 800 a 1.200 unidades.",
      "Ladrillos refractarios para la cámara de combustión — 80 a 120 unidades.",
      "Mortero de barro con 10 % de cal hidráulica.",
      "Puerta hermética de hierro fundido + parrilla.",
      "Chapa galvanizada para el conducto de chimenea interior (luego revestida).",
    ),
    h(2, "Operación"),
    p("Una carga: 8–12 kg de leña seca (cualquier maderable, no requiere quebracho). Se prende, se cierra la puerta cuando hay buen tiro (15 min), y se deja consumir durante 1,5–2 hs. La estufa absorbe el calor; nada se irradia hacia afuera mientras quema."),
    p("4–6 horas después, el cuerpo entra en pleno régimen radiante: a 35–40 °C de temperatura superficial, calienta todo el ambiente por radiación blanda. El banco se mantiene tibio (no quemante) durante 18–24 horas."),
    h(2, "Costo"),
    p("Materiales: USD 600–1.000. Mano de obra especializada: USD 1.500–3.000. Frente a la inversión, un cálculo conservador estima el ahorro en leña en 60–70 % respecto a una salamandra convencional. Amortiza en 3–5 inviernos."),
  ],

  "calefon-solar-termosifon": [
    p("El calefón solar por termosifón es la solución de agua caliente más eficiente y sencilla que existe. Sin bomba, sin electrónica, sin partes móviles. El agua caliente sube sola, el agua fría baja sola — la gravedad y la diferencia de densidad hacen el trabajo. Vida útil 25+ años con mantenimiento mínimo."),
    h(2, "Cómo funciona"),
    p("Un colector solar (tubos al vacío o placa plana) se monta orientado al norte con inclinación = latitud + 10°. Un tanque acumulador termoaislado se ubica por encima del colector — la diferencia de altura mínima entre el tope del colector y la base del tanque debe ser de 30 cm."),
    p("El agua del colector se calienta por radiación solar, se vuelve menos densa y sube por gravedad al tanque. El agua fría del tanque, más densa, baja por la otra cañería hacia el colector. Ciclo continuo, sin energía adicional."),
    h(2, "Componentes para autoconstrucción"),
    ul(
      "Colector de tubos al vacío (recomendado, mayor eficiencia y precio bajado en los últimos años): 20 tubos, USD 250–400.",
      "Tanque acumulador con aislación de poliuretano: 200 L (familia de 4): USD 350–500. Hecho a medida en chapa galvanizada o de acero inoxidable.",
      "Cañerías de cobre o PEX-AL-PEX para resistir temperaturas pico de 95 °C.",
      "Válvula de seguridad de 6 bar.",
      "Termómetro para monitorear.",
    ),
    h(2, "Dimensionamiento"),
    p("La regla simple: 1 m² de colector y 50 L de tanque por persona. Para una familia de 4: 4 m² de colector (1 panel de 20 tubos al vacío) y 200 L de tanque acumulador."),
    p("En zona centro de Argentina, este dimensionamiento cubre el 70–85 % de la demanda anual de agua caliente. El refuerzo eléctrico (resistencia de 1.500 W dentro del tanque, encendida solo si baja de 35 °C) cubre días de baja insolación."),
    h(2, "Instalación"),
    ol(
      "Colocar el colector orientado al norte (entre -15° y +15°), con inclinación 40–45° en zona centro.",
      "Montar el tanque acumulador por encima — idealmente en el techo, sobre soporte aislado.",
      "Conectar las cañerías: salida superior del colector → entrada superior del tanque; salida inferior del tanque → entrada inferior del colector.",
      "Conectar entrada de agua de red (a presión) por la base del tanque, y salida de agua caliente al circuito de la casa.",
      "Llenar, purgar aire, controlar fugas. La puesta en marcha es instantánea — al primer rayo de sol, el ciclo empieza.",
    ),
    h(2, "Costo y amortización"),
    p("Una instalación completa de autoconstrucción cuesta USD 800–1.300. Frente al gas natural (con tarifas EPEC/ECOGAS post Decreto 943/2025), la amortización es de 4–6 años. Frente a un termo eléctrico convencional: 2–3 años."),
  ],

  "fotovoltaica-off-grid": [
    p("Una instalación fotovoltaica off-grid te desconecta de la red eléctrica. Los paneles cargan baterías; las baterías alimentan la casa día y noche; el sistema vive 25 años con mantenimiento mínimo. Es la inversión sustentable con mejor ROI en la Argentina post Decreto 943/2025."),
    h(2, "Cálculo del consumo"),
    p("Antes de dimensionar paneles, hay que conocer el consumo. Una casa eficiente en Argentina consume entre 4 y 8 kWh diarios — heladera, iluminación LED, bombas, electrónica, pequeños electrodomésticos. Calefacción y agua caliente NO se cargan a la electricidad (van a leña + solar térmico)."),
    p("Multiplicar el consumo diario × 1,3 (margen de pérdidas) = energía a generar. Para 6 kWh consumidos: 7,8 kWh a generar."),
    h(2, "Dimensionado de paneles"),
    p("En zona centro de Argentina, las horas-sol-pico promedio anual son 4,5 hs/día. Para generar 7,8 kWh/día: 7,8 / 4,5 = 1,73 kWp instalados."),
    p("Conviene sobredimensionar a 2,2–2,5 kWp para cubrir invierno (3 hs-sol pico). Esto se traduce en 5–6 paneles de 450 W cada uno."),
    h(2, "Banco de baterías"),
    p("La batería se dimensiona para 2–3 días de autonomía (días nublados consecutivos). Para 6 kWh/día × 2 días = 12 kWh netos. Usando baterías de litio LFP (descarga al 90 %), eso son 13,3 kWh nominales — un sistema 48 V × 280 Ah."),
    p("Las baterías de plomo-ácido (descarga 50 %) requieren 24 kWh nominales para la misma autonomía — el doble de capacidad nominal, vida útil 4–6 años. Las LFP duran 10–15 años. La inversión inicial es mayor pero el costo por ciclo es 4 veces menor."),
    h(2, "Inversor"),
    p("Un inversor híbrido off-grid de 3 kW (3.500 W de pico) cubre todos los consumos simultáneos de una casa familiar. Eligir modelo de onda senoidal pura (no modificada) — necesario para electrónica sensible (computadoras, equipos médicos)."),
    h(2, "Costo orientativo (mayo 2026)"),
    ul(
      "Paneles 2,5 kWp + estructura: USD 1.800–2.500",
      "Inversor híbrido 3 kW + accesorios: USD 1.200–1.800",
      "Baterías LFP 13 kWh + BMS: USD 5.000–7.500",
      "Cableado, protecciones, puesta a tierra: USD 500–800",
      "Total: USD 8.500–12.500 + IVA",
    ),
    h(2, "Amortización"),
    p("Con las tarifas EPEC actuales (post pérdida de subsidios), una familia que consumía $80.000–120.000/mes de electricidad ahorra ese gasto. ROI a las tarifas pleno régimen: 4–6 años. Después: 20 años más de electricidad propia, gratuita y silenciosa."),
  ],

  "cocina-rocket-masa": [
    p("La cocina rocket es una estufa de leña miniaturizada que combina alta eficiencia con un costo mínimo. Combustión limpia (sin humo), uso de ramas y leña fina, calor intenso para cocinar. Bien construida, calienta con un puñado de leña que en una salamandra duraría apenas para iniciar el fuego."),
    h(2, "El principio rocket"),
    p("El nombre viene del sonido — una rocket bien armada hace un ruido suave de motor a chorro. Lo provoca la combustión secundaria: los gases volátiles que salen de la madera, al alcanzar 600 °C en la cámara aislada, se vuelven a quemar. Eficiencia: 85 %. Emisiones: similares a una cocina de gas."),
    h(2, "Anatomía"),
    p("Cuatro partes:"),
    ol(
      "Alimentador (cámara vertical donde se introduce la leña).",
      "Cámara de combustión (codo 90° aislado, donde se forma la primera llama).",
      "Riser o chimenea interna (tubo aislado vertical, 50 cm de alto — aquí ocurre la combustión secundaria).",
      "Tope con olla — la transferencia de calor a la olla es máxima por contacto con la llama y el aire muy caliente.",
    ),
    h(2, "Versión con banco térmico"),
    p("La rocket de banco aprovecha el calor sobrante: después del tope de cocción, los gases de escape (todavía a 300+ °C) recorren un conducto horizontal dentro de un banco macizo de tierra o adobe. El banco acumula el calor y lo libera durante 4–8 horas como un asiento tibio."),
    h(2, "Materiales para autoconstrucción"),
    ul(
      "Tubos metálicos de chapa (no galvanizada — el zinc se quema) o ladrillos refractarios para la cámara.",
      "Material aislante: arena vermiculita, perlita expandida, o ceniza de leña — alrededor del riser para mantener temperatura interna.",
      "Tope de cocción: chapa o disco de freno reciclado, o plancha de hierro.",
      "Para el banco: ladrillos comunes + barro + tubos metálicos para el recorrido de los gases.",
    ),
    h(2, "Construcción simplificada (rocket de cocina)"),
    ol(
      "Cortar un bidón metálico de 200 L con tapa, o usar una pared de ladrillos refractarios apilados.",
      "Construir el codo en \"L\" con la cámara de combustión horizontal (20 cm) y el riser vertical (50 cm).",
      "Rodear el riser con material aislante en un cilindro exterior (otra pared de ladrillos o chapa).",
      "Tapar arriba con plancha de hierro perforada para apoyar la olla.",
      "Cargar con leña por la boca lateral; encender en el codo; alimentar manteniendo siempre llama, no brasas.",
    ),
    h(2, "Rendimiento"),
    p("Para hervir 4 L de agua: 10–15 minutos con un puñado de ramas finas. Para cocinar arroz para 6 personas: 25 minutos con 2 kg de leña. La diferencia con una cocina a gas es marginal en velocidad y cero en consumo de leña respecto a un fogón abierto."),
  ],

  /* ── Pisos y Revoques ────────────────────────────────────── */
  "piso-tierra-apisonada": [
    p("Un piso de tierra apisonada es la opción más sustentable, económica y bella que existe para una casa de bioconstrucción. Bien hecho, dura décadas, se puede reparar localmente, regula la humedad, y tiene una textura que ningún otro piso iguala. La técnica es ancestral y simple — pero exige paciencia."),
    h(2, "El material"),
    p("La mezcla básica:"),
    ul(
      "70 % tierra cribada (zarandeada 5 mm) — arcillosa, con bajo contenido orgánico.",
      "20 % arena fina, si la tierra es muy arcillosa.",
      "10 % fibra natural larga: paja picada, viruta de madera, o cáñamo.",
      "Agua: humedad de \"puño cerrado\" — al apretar la mezcla, debe mantener forma sin gotear.",
    ),
    p("Para el último estrato, agregar 5 % de cal hidráulica o aceite de lino al amasado para mejorar la dureza superficial."),
    h(2, "Preparación de la base"),
    p("Sobre tierra natural compactada se coloca:"),
    ol(
      "Capa de aislación capilar: 10 cm de canto rodado lavado.",
      "Aislación higroscópica: una membrana o film de polietileno de 200 micras, solapada 20 cm en uniones.",
      "Capa de regularización: 5 cm de tierra arenosa apisonada.",
    ),
    h(2, "Apisonado"),
    p("Se aplica la mezcla en estratos de 5 cm máximo. Cada estrato se apisona con pisón de 4–6 kg durante 4–6 minutos por metro cuadrado, hasta que el sonido del pisón cambia de \"sordo\" a \"seco\" — señal de compactación adecuada."),
    p("Entre estrato y estrato esperar 24 hs para que el agua superficial migre y la siguiente capa adhiera bien."),
    h(2, "Acabado"),
    p("El último estrato (1,5 cm) se aplica con la mezcla enriquecida (cal + aceite). Se apisona y se alisa con llana metálica mojada. Después se deja secar 5–7 días sin tránsito."),
    p("Curado final: 2–3 manos de aceite de lino caliente aplicado con pincel, dejando 24 hs entre manos. El aceite penetra, polimeriza y endurece la superficie. El piso queda con un brillo satinado, suave al tacto, antideslizante."),
    h(2, "Mantenimiento"),
    p("Año 1: una mano de aceite a los 6 meses. Anual: barrido y trapeado húmedo común. Cada 3–5 años: una mano de aceite de mantenimiento. Reparaciones locales (rayones, hundimientos): se humedece la zona, se aplica mezcla nueva, se apisona, se pule. Indistinguible del original a las pocas semanas."),
  ],

  "revoque-fino-tierra": [
    p("El revoque de tierra fino es el último estrato — el que se ve y se toca. Bien hecho, regula la humedad interior, es repelente al polvo, tiene una belleza visual que se acerca a la cerámica japonesa, y se aplica sobre cualquier soporte: adobe, ladrillo, hormigón, paneles de yeso."),
    h(2, "La mezcla base"),
    p("Las proporciones varían según la tierra disponible, pero una receta confiable para empezar:"),
    ul(
      "50 % arcilla cribada (malla 3 mm) y bien remojada 24 hs antes",
      "30 % arena fina (malla 1–2 mm)",
      "15 % cuarzo molido o tiza para luminosidad superficial",
      "5 % fibras vegetales finas (papel, lino, paja molida) para anclaje",
      "Caseína (leche cuajada con vinagre, 50 ml por kg de mezcla) o aceite de lino crudo como aglutinante natural",
    ),
    h(2, "Pigmentos naturales"),
    p("Sólo pigmentos minerales — los sintéticos cambian con el tiempo y desbalancean el aglutinante natural:"),
    ul(
      "Ocres y siennas (todos los amarillos y marrones)",
      "Óxido de hierro (rojos, marrones oscuros)",
      "Negro de manganeso (gris oscuro)",
      "Verde de tierra de Verona (verde grisáceo suave)",
      "Lapislázuli o azul ultramar natural (azul cobalto, costoso)",
    ),
    p("Proporción del pigmento: 3–8 % del peso de la mezcla seca. Probar antes en una pequeña muestra: la tierra absorbe pigmento de forma distinta a un revoque de cemento."),
    h(2, "Aplicación"),
    ol(
      "Humedecer el soporte la noche anterior, sin saturarlo.",
      "Aplicar con llana de inoxidable en capa de 2–4 mm máximo.",
      "Dejar reposar hasta que la superficie pierda brillo (15–45 min según humedad ambiente).",
      "Alisar y comprimir con espátula de inoxidable o piedra de río — esta etapa, llamada \"bruñido\", es la que da el brillo y la dureza.",
      "Dejar secar 48 hs antes de cualquier contacto.",
    ),
    h(2, "Texturas tradicionales"),
    ul(
      "Estucado japonés (tadelakt): bruñido intenso + sellado con jabón potásico → brillo cerámico, repelente al agua. Ideal para baños y duchas.",
      "Bruñido suave: pasada única con llana, sin compactar. Mate, terrenal.",
      "Texturizado de rodillo: rodillo de esponja para una textura granulada — esconde irregularidades del soporte.",
      "Espatulado libre: pasadas irregulares de espátula — efecto rústico, ideal para muros de adobe que se quieren \"no fingidos\".",
    ),
  ],

  /* ── Planificación ─────────────────────────────────────── */
  "diseno-bioclimatico-10-principios": [
    p("Diseño bioclimático no es agregar paneles solares a una casa convencional. Es pensar la casa entera como un dispositivo termodinámico ajustado a su clima — para que la mayoría del trabajo de climatización lo haga la propia arquitectura, sin energía adicional."),
    h(2, "Los diez principios"),
    p("Aplicables casi universalmente, ajustados al hemisferio sur:"),
    ol(
      "Orientación solar: el lado largo de la casa al norte (entre -15° y +15° respecto al norte verdadero). Los espacios de día (cocina, comedor) al norte, los de noche (habitaciones) al sur o al este.",
      "Compacidad: una planta compacta pierde menos calor en invierno. Relación perímetro/área < 0,4. Las plantas con muchos retranqueos y formas alargadas penalizan.",
      "Inercia térmica: muros pesados (adobe, tapial, ladrillo macizo) en el lado norte y en los muros divisorios internos. Acumulan calor diurno y lo entregan nocturno.",
      "Aislación: techos siempre con aislación generosa — el techo es por donde más calor se pierde en invierno. R = 4 m²K/W mínimo en cubiertas.",
      "Ventilación cruzada: aberturas opuestas, una entrada baja al sur (aire fresco) y una salida alta al norte (aire caliente). Refresca sin energía.",
      "Iluminación natural: ventanas dimensionadas al 15–20 % del área de piso. Tragaluces o tubos solares en zonas profundas.",
      "Protección solar de verano: aleros sobre las ventanas norte calculados para bloquear el sol del solsticio de verano y dejar entrar el del invierno. La fórmula simple: alero = altura ventana × 0,55.",
      "Protección de vientos: arbolado en el lado de los vientos predominantes (en zona centro de Argentina, el suroeste). 3 metros de arbolado bajan la velocidad del viento al 20 % en su lado lee.",
      "Captación de agua: la cubierta y el terreno se diseñan para conducir lluvia hacia tanques y zanjas de infiltración.",
      "Materiales locales: cualquier material que viajó más de 100 km empieza a tener costo ambiental significativo. Adobe, madera, piedra, fibra natural de la zona — siempre primero.",
    ),
    h(2, "El error más común"),
    p("Aplicar uno o dos principios y olvidar el resto. Una casa bioclimática es un sistema: si la orientación está bien pero los muros son livianos sin inercia, el sol entra y se va a la noche. Si los muros son pesados pero el techo no tiene aislación, se acumula calor que se escapa por arriba."),
    p("Los diez principios funcionan en conjunto. No son una checklist a marcar, son un modo de pensar."),
  ],

  "casa-bioclimatica-70m": [
    p("Plano tipo para una casa bioclimática de 70 m² optimizada para la zona centro de Argentina. Pensada como vivienda primaria para una pareja, o secundaria de fin de semana. Eficiente energéticamente, autoconstruible, y dentro del presupuesto de una familia trabajadora."),
    h(2, "Premisas de diseño"),
    ul(
      "Orientación norte estricta — la fachada larga (10 m) al norte.",
      "Galería de 1,80 m de profundidad al norte — alero pasivo para verano + protección de aberturas.",
      "Invernadero adosado al noroeste — captación adicional en invierno, cultivos todo el año.",
      "Muros norte con muro Trombe parcial (4 m²).",
      "Techo con aislación de lana de oveja (15 cm) + cubierta vegetal extensiva opcional.",
    ),
    h(2, "Programa (70 m² netos)"),
    ul(
      "Cocina-comedor integrado al norte: 22 m².",
      "Estar con muro Trombe al norte: 16 m².",
      "2 habitaciones al sur: 11 m² + 9 m² = 20 m².",
      "Baño compacto interior: 4 m².",
      "Lavadero y depósito: 5 m².",
      "Galería cubierta norte: 18 m² (no cuenta como m² cubierto).",
      "Invernadero adosado: 8 m² (no cuenta como m² cubierto).",
    ),
    h(2, "Sistema constructivo"),
    p("Quincha mejorada para todos los muros perimetrales (verificable CIRSOC 601). Muro Trombe parcial en el norte (adobe macizo de 30 cm, vidriado DVH separación 12 cm). Tabiques internos en bahareque o panel de yeso sobre estructura de madera."),
    h(2, "Energía"),
    ul(
      "Solar térmico (4 m² de tubos al vacío + 200 L tanque): cubre 80 % del agua caliente.",
      "Fotovoltaica off-grid 2 kWp + LFP 6 kWh: cubre 100 % de electricidad año redondo.",
      "Calefacción: estufa rusa de 1.500 kg en el centro de la casa (entrega calor a estar + comedor + tira de 1 m al pasillo norte).",
      "Cocina: cocina rocket + cocina a gas con garrafa (backup).",
    ),
    h(2, "Costo orientativo (mayo 2026)"),
    ul(
      "Construcción quincha + Trombe + cubierta: USD 56.000–80.000",
      "Instalaciones (solar térmico + fotovoltaica + agua): USD 14.000–18.000",
      "Total schlüsselfertig: USD 70.000–98.000 = USD 1.000–1.400/m²",
      "Con autoconstrucción y mingas: USD 45.000–60.000 = USD 640–860/m²",
    ),
    p("El plano completo incluye memoria descriptiva, planos arquitectónicos, cortes, detalles constructivos y cómputo de materiales. Es descargable desde la biblioteca como PDF."),
  ],

  "presupuesto-construir-en-tierra-2026": [
    p("Una pregunta que recibimos todas las semanas: \"¿cuánto cuesta construir en tierra?\". La respuesta corta es \"menos que en hormigón, pero depende\". La larga es este artículo — con números reales, fuentes verificables y rangos honestos."),
    h(2, "Referencia: construcción convencional Córdoba"),
    p("El Colegio de Arquitectos de la Provincia de Córdoba (CAPC) publica trimestralmente el costo de una vivienda unifamiliar tipo. Octubre 2025:"),
    ul(
      "Construcción húmeda tradicional, completo: $ 1.632.000/m² (≈ USD 1.145/m² al cambio oficial mayo 2026).",
      "Construcción en seco (steel frame), completo: $ 1.760.000/m² (≈ USD 1.235/m²).",
      "Vivienda social mínima (ICC-Córdoba): $ 873.000/m² (≈ USD 613/m²).",
    ),
    h(2, "Bioconstrucción en Sierras de Córdoba"),
    p("No hay un índice oficial. Los rangos siguientes provienen de obras propias de Hombre de Barro, del Taller TABI (FAUD-UNC) y de la Red Argentina de Construcción Sustentable:"),
    ul(
      "Adobe + cubierta de chapa, completo con honorarios: $ 1.150.000–1.400.000/m² (USD 800–980/m²).",
      "Quincha mejorada + cubierta de chapa, completo: $ 1.100.000–1.350.000/m² (USD 770–950/m²).",
      "Cob esculpido + cubierta de paja: $ 950.000–1.200.000/m² (USD 670–840/m²).",
      "Superadobe con cúpula: $ 900.000–1.150.000/m² (USD 630–810/m²).",
    ),
    p("Promedio para el comparador: $ 1.250.000/m² completo, o aproximadamente USD 875/m² al cambio mayo 2026. Eso significa un 23 % menos que la construcción convencional CAPC."),
    h(2, "Autoconstrucción"),
    p("Una persona que aporta mano de obra propia (con asesoría profesional periódica) reduce el costo otro 20–30 %. La autoconstrucción no significa hacer la obra solo desde el primer día — es contratar lo crítico (cimientos, estructura, instalaciones) y aportar la propia mano para todo lo que no requiere especialización (muros, revoques, terminaciones)."),
    h(2, "Inversión adicional sustentable"),
    ul(
      "Solar fotovoltaica off-grid 3–5 kW con baterías: USD 6.500–14.000 (≈ $ 9–20 millones)",
      "Solar térmico (calefón solar): USD 1.000–2.000",
      "Captación pluvial + filtros + fitodepuración: USD 2.500–4.500",
      "Total instalaciones sustentables: USD 10.000–20.000 (≈ $ 14–28 millones)",
    ),
    p("Esta inversión adicional se amortiza en 4–7 años con las tarifas EPEC/ECOGAS post Decreto 943/2025."),
    h(2, "Costo total de un proyecto típico"),
    p("Vivienda bioclimática de 100 m² en Sierras de Córdoba:"),
    ul(
      "Construcción base (quincha o adobe): USD 87.500",
      "Instalaciones sustentables: USD 15.000",
      "Honorarios y dirección de obra: USD 8.500",
      "Total: USD 111.000 (≈ $ 158 millones a mayo 2026)",
      "Equivalente convencional CAPC: USD 142.000 — diferencia: USD 31.000 menos.",
    ),
    p("Y de ahí en más: 0–80.000 pesos mensuales en servicios, contra 230.000–340.000 de una vivienda convencional. El verdadero ahorro empieza el día 1 de habitar."),
  ],

  "tramites-construccion-natural": [
    p("La construcción con tierra en Argentina existe en un limbo normativo. No está prohibida — pero tampoco está claramente regulada a nivel nacional. La situación varía dramáticamente entre municipios. Esta guía te orienta sobre qué hacer dónde."),
    h(2, "El panorama nacional"),
    p("No hay una ley federal de bioconstrucción. Los reglamentos que aplican son los generales:"),
    ul(
      "Reglamento CIRSOC 601: construcciones sismo-resistentes. Aplica a toda la Argentina. No prohíbe la tierra, pero exige verificación estructural para zonas sísmicas 2 a 4.",
      "Norma IRAM 11.605: aislación térmica de viviendas. Aplica a todas las construcciones. La construcción con tierra cumple con holgura.",
      "Reglamentos municipales: códigos de edificación. Aquí está el verdadero desafío.",
    ),
    h(2, "Municipios habilitantes"),
    p("Existen municipios donde la bioconstrucción está explícitamente reglamentada y se aprueba sin objeciones:"),
    ul(
      "El Bolsón (Río Negro): pionero, reglamento desde 2007.",
      "General Pueyrredón (Buenos Aires): habilita adobe y tierra con cálculo estructural firmado.",
      "Beltrán (Río Negro): incluye bioconstrucción en su código municipal.",
      "San Carlos de Bariloche: aprueba en lotes rurales con dirección técnica.",
      "La Serranita (Córdoba): permisivo, varios precedentes.",
      "Salsipuedes y Villa Sol (Córdoba): zonas con barrios bioarquitectónicos consolidados.",
    ),
    h(2, "Estrategia en municipios sin reglamento específico"),
    p("La mayoría de los municipios argentinos no tienen un capítulo específico para bioconstrucción. La estrategia que recomendamos:"),
    ol(
      "Conseguir un arquitecto matriculado con experiencia en bioarquitectura (Hombre de Barro tiene matrícula activa en CAPC).",
      "Presentar el proyecto como \"vivienda con muros de tierra cruda con verificación estructural según CIRSOC 601\". Incluir memoria de cálculo y planos.",
      "Acompañar con ensayos de resistencia del adobe o de la quincha (laboratorios universitarios — TABI en FAUD-UNC realiza estos ensayos).",
      "Para municipios reticentes, conviene una reunión técnica previa al ingreso del expediente. La mayoría de los rechazos vienen de desconocimiento, no de prohibición real.",
    ),
    h(2, "Ensayos requeridos"),
    p("Algunos municipios piden ensayos puntuales. Los más solicitados:"),
    ul(
      "Resistencia a compresión simple del bloque/probeta — debe superar 1,2 MPa (mucho menos de lo que entrega un adobe bien hecho).",
      "Absorción de agua: < 20 % en 24 hs.",
      "Resistencia sísmica del conjunto: ensayo en mesa vibratoria (caro y poco frecuente).",
    ),
    p("Estos ensayos los realizan TABI (Córdoba), INTI Construcciones (Buenos Aires), y algunos laboratorios universitarios provinciales."),
    h(2, "Honorarios del arquitecto"),
    p("Para construcción con tierra, los honorarios estándar del CAPC se aplican igual que en obra tradicional: 6–8 % del valor de obra para proyecto + dirección. No hay ningún descuento ni penalización por el sistema constructivo elegido."),
  ],
};
